version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Montar tu archivo de configuración de Nginx
    depends_on:
      - web
    networks:
      - webnet  # Definir red compartida
    restart: always  # Para reiniciar automáticamente en caso de fallo

  web:
    image: php:8.3-apache
    deploy:
      replicas: 15  # Escalar a 15 instancias del servicio
    volumes:
      - ./index.html:/var/www/html/index.html  # Asegurar que el HTML esté accesible
      - ./app:/var/www/html  # Asegurar que la aplicación PHP/HTML esté en el contenedor
    networks:
      - webnet  # Conectar los contenedores web a la misma red
    restart: always  # Para reiniciar automáticamente en caso de fallo

networks:
  webnet:  # Definir la red para la comunicación
    driver: bridge  # Usar la red 'bridge' para contenedores que necesitan comunicación interna
